version: '3.9'

services:
  tracker:
    image: maeldieudonne/mlops:latest
    depends_on:
      - db
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - OPENAI_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_S3_ENDPOINT
      - AWS_DEFAULT_REGION
      - PYTHONPATH=/app
    volumes:
      - ./tracker/logs:/app/logs
    restart: no
    command: ["/bin/bash", "-c", "until pg_isready -h db -p 5432; do echo 'Waiting for database...'; sleep 5; done && /app/venv/bin/python setup/db_init.py && /app/venv/bin/python scheduler.py"]
    networks:
      - mlops-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
    - ./db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: no
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge